# Generated by Django 3.0.1 on 2022-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='is_sold',
            field=models.BooleanField(default=True),
        ),
    ]
