# Generated by Django 3.0.1 on 2022-01-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='is_sold',
        ),
    ]
