# Generated by Django 3.0.1 on 2022-01-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='num_of_ratings',
            field=models.IntegerField(default=1),
        ),
    ]
