# Generated by Django 3.0.1 on 2022-02-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_num_of_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='num_of_ratings',
        ),
    ]
