# Generated by Django 3.2 on 2022-01-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20220101_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=6),
            preserve_default=False,
        ),
    ]
