# Generated by Django 3.0.1 on 2022-01-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20220108_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
