# Generated by Django 3.0.1 on 2022-02-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20220219_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_added',
        ),
    ]
