# Generated by Django 3.0.1 on 2022-01-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_work_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='is_sold',
            field=models.BooleanField(),
        ),
    ]
