# Generated by Django 3.0.1 on 2022-02-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20220219_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
