# Generated by Django 3.0.1 on 2022-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20220109_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
