# Generated by Django 3.0.1 on 2022-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20220115_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
