# Generated by Django 3.0.1 on 2022-02-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='rating',
        ),
    ]
