# Generated by Django 3.0.1 on 2022-02-20 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_remove_work_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
