# Generated by Django 3.0.1 on 2022-01-20 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20220118_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
