# Generated by Django 3.0.1 on 2022-02-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.Work'),
        ),
    ]
