# Generated by Django 3.0.1 on 2022-02-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_review_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
