# Generated by Django 3.0.1 on 2022-01-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20220121_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Is_sold',
        ),
    ]
