# Generated by Django 3.0.1 on 2022-01-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_auto_20220122_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
