# Generated by Django 3.0.1 on 2022-02-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
