# Generated by Django 3.0.1 on 2022-02-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_remove_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='rating',
        ),
    ]
