# Generated by Django 3.0.1 on 2022-01-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20220122_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='work',
            name='user_rating',
        ),
    ]
