# Generated by Django 3.0.1 on 2022-01-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0018_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Ratings'},
        ),
    ]
