# Generated by Django 3.0.1 on 2022-01-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_auto_20220122_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
