# Generated by Django 3.0.1 on 2022-02-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_auto_20220223_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
