# Generated by Django 3.0.1 on 2022-02-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0020_auto_20220223_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
