# Generated by Django 3.0.1 on 2022-02-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0022_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
