# Generated by Django 3.0.1 on 2022-01-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0022_auto_20220123_0227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
